### ISSUE TITLE
Crash on login_with_permissions on Android devices with "britzl/defold-sharing" plugin

### ISSUE THREAD

**Issue by Dr-Klaus** [defold/extension-facebook#40]
Tested on 2 android devices and with the following plugins:
defold/extension-iap - WORKED, NO CRASH
defold/extension-admob - WORKED, NO CRASH
AGulev/DefVideoAds - WORKED, NO CRASH
britzl/defold-screenshot - WORKED, NO CRASH

britzl/defold-sharing - CRASH on executing login_with_permissions

log:
```
08-18 20:07:56.172  7872  7872 E AndroidRuntime: FATAL EXCEPTION: main
08-18 20:07:56.172  7872  7872 E AndroidRuntime: Process: com.xiart.fb.solitaire, PID: 7872
08-18 20:07:56.172  7872  7872 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/runtime/R$id;
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at androidx.lifecycle.ViewTreeLifecycleOwner.set(ViewTreeLifecycleOwner.java:49)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at androidx.activity.ComponentActivity.initViewTreeOwners(ComponentActivity.java:408)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at androidx.activity.ComponentActivity.setContentView(ComponentActivity.java:379)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at com.facebook.FacebookActivity.onCreate(FacebookActivity.java:82)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7893)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7880)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3313)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3487)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7561)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.runtime.R$id" on path: DexPathList[[zip file "/data/app/com.xiart.fb.solitaire-J4KiXCO64xdO4NM2i7zRWA==/base.apk"],nativeLibraryDirectories=[/data/app/com.xiart.fb.solitaire-J4KiXCO64xdO4NM2i7zRWA==/lib/arm64, /data/app/com.xiart.fb.solitaire-J4KiXCO64xdO4NM2i7zRWA==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:230)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-18 20:07:56.172  7872  7872 E AndroidRuntime: 	... 19 more
```

**Comment by britzl** [comment]
Released a new version of defold-sharing with updated gradle dependencies:

https://github.com/britzl/defold-sharing/releases/tag/4.1.0
